#%RAML 1.0 DocumentationItem
title: DoiT International Salesforce Sys API
content: |
  This API contains functionality that allows developers to Create/Update or GET the data of **_Contact_**, **_Account_**, **_Opportunity_**, **_Lead_** and **_Task_** from Salesforce.

  Available Endpoints and Methods Are:
  1. /Contact:- 
  2. /Account:- 
  3. /Opportunity:- 
  4. /Lead :- 
  5. /Task :- 
  6. /User :-

  Author : Apisero                                   
  Project : DoiT          
  API : DoiT Salesforce System API